import { MailService } from '@sendgrid/mail';

if (!process.env.SENDGRID_API_KEY) {
  console.warn("SENDGRID_API_KEY environment variable not set - emails will be logged to console only");
}

const mailService = new MailService();
if (process.env.SENDGRID_API_KEY) {
  mailService.setApiKey(process.env.SENDGRID_API_KEY);
}

interface EmailParams {
  to: string;
  from: string;
  subject: string;
  text?: string;
  html?: string;
}

export async function sendEmail(params: EmailParams): Promise<boolean> {
  if (!process.env.SENDGRID_API_KEY) {
    console.log('📧 EMAIL (Development Mode - No SendGrid API Key)');
    console.log(`To: ${params.to}`);
    console.log(`From: ${params.from}`);
    console.log(`Subject: ${params.subject}`);
    console.log(`HTML: ${params.html || params.text}`);
    console.log('---');
    return true;
  }

  try {
    await mailService.send({
      to: params.to,
      from: params.from,
      subject: params.subject,
      text: params.text,
      html: params.html,
    });
    console.log(`✅ Email sent successfully to ${params.to}`);
    return true;
  } catch (error) {
    console.error('❌ SendGrid email error:', error);
    return false;
  }
}

// Quote email template
export function generateQuoteEmailHTML(
  customerName: string,
  quoteDetails: any,
  businessName: string = "Portrait Photography Studio"
): string {
  return `
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Your Photography Quote</title>
        <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
            .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0; }
            .content { background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px; }
            .quote-summary { background: white; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #667eea; }
            .price { font-size: 24px; font-weight: bold; color: #667eea; text-align: center; margin: 20px 0; }
            .breakdown { margin: 15px 0; }
            .breakdown-item { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #eee; }
            .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #666; }
            .cta-button { display: inline-block; background: #667eea; color: white; padding: 12px 30px; text-decoration: none; border-radius: 6px; margin: 20px 0; }
        </style>
    </head>
    <body>
        <div class="header">
            <h1>📸 Your Photography Quote</h1>
            <p>Thank you for choosing ${businessName}</p>
        </div>
        
        <div class="content">
            <p>Dear ${customerName},</p>
            
            <p>Thank you for your interest in our photography services! We're excited to capture your special moments.</p>
            
            <div class="quote-summary">
                <h3>📋 Quote Summary</h3>
                <div class="breakdown">
                    ${quoteDetails.breakdown.map((item: string) => `
                        <div class="breakdown-item">
                            <span>${item.split(': ')[0]}</span>
                            <span><strong>${item.split(': ')[1]}</strong></span>
                        </div>
                    `).join('')}
                </div>
                
                <div class="price">
                    Total: ${quoteDetails.currencySymbol}${quoteDetails.total}
                </div>
            </div>
            
            <div style="text-align: center;">
                <a href="#" class="cta-button">Book Your Session</a>
            </div>
            
            <h3>🎯 What's Included:</h3>
            <ul>
                <li>Professional photography session</li>
                <li>High-resolution edited photos</li>
                <li>Online gallery for easy sharing</li>
                <li>Personal consultation</li>
            </ul>
            
            <p><strong>Next Steps:</strong></p>
            <ol>
                <li>Reply to confirm your booking</li>
                <li>We'll schedule your session</li>
                <li>Receive your beautiful photos!</li>
            </ol>
            
            <p>We look forward to working with you!</p>
            
            <p>Best regards,<br>
            <strong>${businessName}</strong></p>
        </div>
        
        <div class="footer">
            <p>This quote is valid for 30 days. Generated by QuoteKit.ai</p>
        </div>
    </body>
    </html>
  `;
}